services:
  italian-bot:
    build: bots/italiano
    container_name: italian-learning-bot
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: "${IT_TELEGRAM_BOT_TOKEN}"
      TELEGRAM_CHAT_IDS: "${IT_ALLOWED_USER_IDS:-}"
      SEND_TIMES: "${IT_SEND_TIMES:-09:00,14:00,20:00}"
      TZ: "${TZ:-Europe/Paris}"
      MISTRAL_API_KEY: "${MISTRAL_API_KEY}"
      MISTRAL_HTTP_TIMEOUT: "${MISTRAL_HTTP_TIMEOUT:-60}"
      MISTRAL_FORCE_IPV4: "${FORCE_IPV4:-true}"
      TELEGRAM_FORCE_IPV4: "${FORCE_IPV4:-true}"
      TELEGRAM_HTTP_TIMEOUT: "${TELEGRAM_HTTP_TIMEOUT:-5}"
      MISTRAL_MODEL: "${MISTRAL_MODEL:-mistral-small-latest}"
      WORDS_PATH: "/app/words.json"
      SUBSCRIBERS_PATH: "/data/subscribers.json"
    volumes:
      - ./bots/italiano/app/words.json:/app/words.json:ro
      - ./bots/italiano/data:/data

  where-based-bot:
    build: bots/where-based
    container_name: where-based-bot
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: "${WB_TELEGRAM_BOT_TOKEN}"
      ALLOWED_USER_IDS: "${WB_ALLOWED_USER_IDS:-}"
      MISTRAL_API_KEY: "${MISTRAL_API_KEY}"
      MISTRAL_HTTP_TIMEOUT: "${MISTRAL_HTTP_TIMEOUT:-60}"
      MISTRAL_MODEL: "${MISTRAL_MODEL:-mistral-small-latest}"
      FORCE_IPV4: "${FORCE_IPV4:-true}"
      TELEGRAM_HTTP_TIMEOUT: "${TELEGRAM_HTTP_TIMEOUT:-5}"
      SUBSCRIBERS_PATH: "/data/subscribers.json"
    volumes:
      - ./bots/where-based/data:/data
